version: "3"
services:
  tcp-server:
    restart: always
    build: ./flask_app
    command: python3 -u ./flask_app/app.py
    ports:
      - "443:443"
    volumes:
      - .:/cleverest_machine
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database
  database:
    restart: always
    image: mongo:3.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    mongo-express:
      restart: always
      image: mongo-express
      environment:
        - ME_CONFIG_MONGODB_SERVER=database
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
        - ME_CONFIG_MONGODB_AUTH_DATABASE=entrance
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=VeryHardToHack098
      ports:
        - "8081:8081"
      links:
        - database
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "10"
      depends_on:
        - database